"""What counts as what in the codebase charts, decided over the facts facts.py measured.

A Snapshot answers every definition for one snapshot of Drupal Core, each a property computed the
first time something reads it; fields() gathers the ones data.json carries, and explain.py lists
the items behind any of them. The sections follow the charts: files, code classification, lines of
code, dependencies, complexity, class cohesion, antipatterns, hotspots, type coverage, deprecations,
surface area and YAML formats.
"""
from __future__ import annotations

import collections
import re
from decimal import ROUND_HALF_UP, Decimal
from functools import cached_property
from typing import NamedTuple, Optional

from facts import Content, Declaration, Entry, JavaScriptContent, PhpContent, StringKey, YamlContent

# Test code: a directory whose name starts or ends with test or Test (tests, simpletest, Testing),
# a *Test.php or *TestBase.php class, or a Drupal 7 .test file.
TEST_CODE = re.compile(r"(^|/)([Tt]est[^/]*|[^/]*[Tt]est)/|Test(Base)?\.php$|\.test$")

CLASS_LIKE_KINDS = {"class", "interface", "trait", "enum"}

# The interface a class implements to subscribe to events, named as the code resolves it.
EVENT_SUBSCRIBER_INTERFACE = "Symfony\\Component\\EventDispatcher\\EventSubscriberInterface"

# How many functions and how many classes the hotspot tables rank, as concrete refactoring targets.
HOTSPOT_COUNT = 50

# The places Core kept third-party JavaScript beside its own until it moved it to core/assets/vendor in
# June 2013 (#1473066), and VIE, Create.js, picturefill and Joyride, which left Core around that move.
# Every library since sits in assets/vendor, which the rules leave out, so this list of history cannot grow.
BUNDLED_JAVASCRIPT = ("misc/ui/", "misc/vie/", "misc/create/", "misc/backbone/", "misc/underscore/", "misc/modernizr/",
                      "misc/farbtastic/", "misc/ckeditor/", "modules/picture/picturefill/", "modules/tour/js/jquery.joyride",
                      "misc/jquery.js", "misc/jquery.form.js", "misc/jquery.once.js", "misc/jquery.ba-bbq.js",
                      "misc/jquery.cookie.js", "misc/jquery.ui.touch-punch.js", "misc/html5.js")


class File(NamedTuple):
    """A file of a snapshot, its path relative to the snapshot's root."""
    prefix: str
    path: str
    content: Optional[Content]


class Function(NamedTuple):
    """A function or method with a body, its position among its file's declarations, the name
    hotspots show, and the antipatterns scored inside it."""
    file: File
    declaration: Declaration
    position: int
    name: str
    antipatterns: int


class Score(NamedTuple):
    """An antipattern found in a file, scored for the function it sits in, or None at file level."""
    pattern: str
    file: File
    function: Optional[Declaration]
    score: int


def is_test_code(path: str) -> bool:
    return TEST_CODE.search(path) is not None


def is_generated(file: File) -> bool:
    """A generated file says so in its opening comments ("This file was generated by the
    dump-database-d6.sh tool", "THIS IS A GENERATED FILE"); only those comments count, since the
    proxy class generator carries the words in its template."""
    return re.search(r"this (file was|is a) generated", file.content.opening_comments, re.IGNORECASE | re.ASCII) is not None


def distinct(files: collections.abc.Iterable[File]) -> list[File]:
    """Identical content once, at its first path in sorted order. The CVS-to-git migration rebuilt each
    renamed file's history under its final name too, so from 2001 to 2006 git holds copies no release
    contained: modules/node.module beside modules/node/node.module, and import.module beside
    aggregator.module, the name it took in 2004. Production and tests are counted apart, because a copy
    is of one kind or the other, and counting them together let a test module swallow a production file:
    in 2013 twenty test modules held an opening tag and nothing else, as serialization.module did."""
    first = {}
    for file in sorted(files, key=lambda file: file.path):
        first.setdefault(file.content, file)
    return list(first.values())


def base_name(path: str) -> str:
    return path.rpartition("/")[2]


def directory_name(path: str) -> str:
    """The directory holding a path, '.' for a file at the root."""
    return path.rpartition("/")[0] or "."


def two_decimals(value: float) -> float | int:
    """Rounded to two decimals, half away from zero, on the shortest decimal that reads back as the
    value, so 0.285 rounds up although its double is a hair below it. A whole number stays an
    integer, as data.json has always written it."""
    rounded = Decimal(repr(value)).quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)
    return int(rounded) if rounded == rounded.to_integral_value() else float(rounded)


def yaml_format(extension: str, path: str) -> Optional[str]:
    """The YAML format a file inside an extension belongs to, or None. At the extension's root,
    <name>.<format>.yml (routing, links.menu). Below it, <item>.<format>.yml (components), or a plain
    .yml file named by the top directory holding it (migrations, layouts). config/schema holds schema
    however its files are named (ckeditor5.data_types.yml); the rest of config/ holds configuration
    objects, the data an extension installs, not a format."""
    inside = path[len(extension) + 1:].split("/")[:-1]
    if inside[:1] == ["config"]:
        return "schema" if inside[1:2] == ["schema"] else None
    segments = base_name(path).removesuffix(".yml").split(".")
    if not inside:
        return ".".join(segments[1:]) if segments[0] == base_name(extension) and len(segments) > 1 else None
    return segments[-1] if len(segments) > 1 else inside[0]


def hook_implementations(content: PhpContent) -> set[Declaration]:
    """The declarations a file's #[Hook] attributes mark: one carrying the attribute, and the method
    a class's attribute names by the method argument, named or second, or __invoke when that is empty.
    Method names are case-insensitive in PHP."""
    implementations = set()
    for declaration in content.declarations:
        for attribute in declaration.attributes:
            if attribute.name != "Drupal\\Core\\Hook\\Attribute\\Hook":
                continue
            implementations.add(declaration)
            method = next((argument.value for position, argument in enumerate(attribute.arguments)
                           if argument.name == "method" or (argument.name is None and position == 1)), None)
            implementations.update(child for child in content.declarations
                                   if child.parent is declaration and child.name.lower() == (method or "__invoke").lower())
    return implementations


class Snapshot:
    """The definitions, answering for one snapshot's files."""

    def __init__(self, entries: tuple[Entry, ...]):
        self.entries = entries

    # =============================================================================
    # FILES
    # =============================================================================

    @cached_property
    def files(self) -> list[File]:
        """The files the analysis reads, with paths relative to the snapshot's root: core/ once
        Drupal 8 moved Core's code there, the whole tree before. Every rule about Drupal's code reads
        paths from here; dependencies read the lock, which sits at the repository root."""
        prefix = "core/" if any(entry.path.startswith("core/") for entry in self.entries) else ""
        return [File(prefix, entry.path.removeprefix(prefix), entry.content)
                for entry in self.entries if entry.path.startswith(prefix)]

    @cached_property
    def own_files(self) -> list[File]:
        """Drupal's own files. Third-party code sits in the two directories at the snapshot's root that
        hold it: vendor/, and assets/, where Core keeps compiled and third-party front-end files. A
        directory of either name deeper in the tree is Core's own, as core/scripts/js/assets is."""
        return [file for file in self.files if file.path.split("/")[0] not in {"vendor", "assets"}]

    @cached_property
    def php_sources(self) -> list[File]:
        """PHP files holding Drupal's own code or tests. Left out besides what own_files leaves out:
        the libraries Drupal once bundled in its own tree (XML-RPC for PHP, XTemplate, PEAR's
        Archive_Tar, the Doctrine annotation parser), the .api.php files that document hooks, and
        .tpl.php templates, whose Twig successors are not counted either, so the conversion would
        read as code removed."""
        return [file for file in self.own_files
                if isinstance(file.content, PhpContent)
                and "Doctrine" not in file.path.split("/")[:-1]
                and base_name(file.path) not in {"xmlrpc.inc", "xmlrpcs.inc", "xtemplate.inc", "system.tar.inc",
                                                 "ArchiveTar.php"}
                and not file.path.endswith((".api.php", ".tpl.php"))]

    # =============================================================================
    # CODE CLASSIFICATION
    # =============================================================================

    @cached_property
    def production_php(self) -> list[File]:
        """Production PHP: Drupal's own code, not tests, not generated, and not a file of literal values
        that declares and calls nothing (transliteration tables, sites.php examples)."""
        return distinct(file for file in self.php_sources
                        if not is_generated(file) and not is_test_code(file.path) and not file.content.literal_only)

    @cached_property
    def test_php(self) -> list[File]:
        """Test PHP, by the rules production follows. Test fixtures are data rather than tests: whole
        Drupal 6 and 7 databases dumped as PHP arrays, left out by their directory, and so is a file of
        literal values, as core's test module and test theme stubs are."""
        return distinct(file for file in self.php_sources
                        if not is_generated(file) and is_test_code(file.path) and not file.content.literal_only
                        and "fixtures" not in file.path.split("/")[:-1])

    @cached_property
    def unparsed_production_php(self) -> list[File]:
        """Production files no PHP version parses: their lines count, and they declare nothing."""
        return [file for file in self.production_php if file.content.parse == "failed"]

    # =============================================================================
    # LINES OF CODE
    # =============================================================================

    @cached_property
    def production_lines(self) -> int:
        return sum(file.content.code_line_count for file in self.production_php)

    @cached_property
    def object_oriented_lines(self) -> int:
        """Production lines by paradigm. The extractor measures which code lines sit inside a
        class-like, and which inside a function outside any class-like. A line in a class, interface,
        trait or enum is object-oriented; a line in a function is procedural; the lines at file level
        (use statements, file-level code) follow the file, object-oriented when it declares a
        class-like of its own. Deciding per file counted all of 2011's node.module as object-oriented
        because it declared one class, and an anonymous class, an inline throwaway a procedural file
        builds like any other value, is not a class the file declares."""
        def object_oriented(content: PhpContent) -> int:
            file_level = content.code_line_count - content.class_like_line_count - content.function_line_count
            declares_class_like = any(declaration.kind in CLASS_LIKE_KINDS and declaration.name is not None
                                      for declaration in content.declarations)
            return content.class_like_line_count + (file_level if declares_class_like else 0)
        return sum(object_oriented(file.content) for file in self.production_php)

    @cached_property
    def test_lines(self) -> int:
        return sum(file.content.code_line_count for file in self.test_php)

    @cached_property
    def production_javascript(self) -> list[File]:
        """Production JavaScript and TypeScript: Drupal's own files, without test code, minified files and
        the third-party libraries Core kept beside them (BUNDLED_JAVASCRIPT). Counting VIE, Create.js
        and picturefill drew a JavaScript spike at the end of 2012 that was not Drupal's code, while the
        jquery.* name rule it replaces left out Drupal's own shims. From 2017 to 2022 Core
        kept its JavaScript as .es6.js sources compiled into a .js twin; the source is what people
        wrote, so the twin is left out. Counting the compiled file put a 17% step in the series when
        Core dropped the build in 2022 (#3278415)."""
        paths = {file.path for file in self.files}
        return [file for file in self.own_files
                if isinstance(file.content, JavaScriptContent)
                and not file.path.endswith(".min.js")
                and file.path[:-3] + ".es6.js" not in paths
                and not file.path.startswith(BUNDLED_JAVASCRIPT)
                and not is_test_code(file.path)]

    @cached_property
    def javascript_lines(self) -> int:
        return sum(file.content.code_line_count for file in self.production_javascript)

    # =============================================================================
    # DEPENDENCIES
    # =============================================================================

    @cached_property
    def dependencies(self) -> Optional[dict]:
        """Third-party Composer packages in the lock, direct and transitive, leaving out Drupal's own
        (drupal/core and its Composer plugins). The lock sat in core/ before settling at the repository
        root at different times, never both at once. A lock written before Composer split out development packages has
        no development count, which is not the same as zero."""
        def third_party(names: Optional[tuple[str, ...]]) -> Optional[int]:
            return None if names is None else sum(not name.startswith("drupal/") for name in names)
        for entry in self.entries:
            if entry.path in ("composer.lock", "core/composer.lock"):
                if entry.content.valid:
                    return {"production": third_party(entry.content.packages),
                            "development": third_party(entry.content.development)}
        return None

    # =============================================================================
    # COMPLEXITY
    # =============================================================================

    @cached_property
    def production_declarations(self) -> list[tuple[File, Declaration]]:
        """Declarations in production PHP, each with its file."""
        return [(file, declaration) for file in self.production_php for declaration in file.content.declarations]

    @cached_property
    def production_functions(self) -> list[Function]:
        """The functions complexity is measured over: every function, and every method with a body.
        Interface and abstract signatures have nothing to read; counting them scored thousands of zeros,
        more with every interface Drupal 8 added, and pulled the average down."""
        scores = collections.Counter()
        for score in self.antipattern_scores:
            scores[score.function] += score.score
        functions = []
        for file in self.production_php:
            for position, declaration in enumerate(file.content.declarations):
                if declaration.has_body:
                    name = declaration.name
                    if declaration.kind == "method":
                        name = f"{declaration.parent.name or 'anonymous'}::{declaration.name}"
                    functions.append(Function(file, declaration, position, name, scores[declaration]))
        return functions

    @cached_property
    def cognitive_complexity(self) -> dict:
        """Cognitive complexity across production functions: their average, and the value at the 95th
        percentile, the ceil(95 n / 100)-th smallest."""
        scores = sorted(function.declaration.cognitive for function in self.production_functions)
        if not scores:
            return {"average": None, "percentile95": None}
        return {"average": two_decimals(sum(scores) / len(scores)), "percentile95": scores[(95 * len(scores) + 99) // 100 - 1]}

    # =============================================================================
    # CLASS COHESION
    # =============================================================================

    @cached_property
    def class_cohesion(self) -> Optional[float | int]:
        """Class cohesion: LCOM4 averaged over named classes, traits and enums with a method body.
        Interfaces have no method bodies, so no LCOM4, and anonymous classes are inline throwaways."""
        values = [declaration.lcom4 for _, declaration in self.production_declarations
                  if declaration.lcom4 is not None and declaration.name is not None]
        return two_decimals(sum(values) / len(values)) if values else None

    # =============================================================================
    # ANTIPATTERNS
    # =============================================================================

    @cached_property
    def magic_key_uses(self) -> list[tuple[File, StringKey]]:
        """Magic keys: '#'-prefixed array keys naming a render-array property, in an access
        ($form['x']['#access']) or a literal (['#theme' => ...]), which trigger behavior a developer has
        to know by name. Capitals are allowed after the first letter, for #propsAlter and #slotsAlter. A
        '#' key naming no property is data: Garland's color schemes keyed by '#ffe23d,#a9290a,...' until
        2010, route patterns in a regular expression since 2024."""
        return [(file, use) for file in self.production_php for use in file.content.string_keys
                if re.fullmatch(r"#[a-z][a-zA-Z0-9_]*", use.name, re.ASCII)]

    @cached_property
    def antipattern_scores(self) -> list[Score]:
        """Each magic key scores 1. Deep arrays: an access chain or array literal nested more than two
        deep scores its depth beyond two. Service locators: \\Drupal:: calls and ->container->get(),
        which fetch a dependency instead of receiving it, score 1."""
        return [
            *(Score("magicKeys", file, use.function, 1) for file, use in self.magic_key_uses),
            *(Score("deepArrays", file, depth.function, (depth.depth - 2) * depth.occurrences)
              for file in self.production_php for depth in file.content.array_depths if depth.depth >= 3),
            *(Score("serviceLocators", file, call.function, 1)
              for file in self.production_php for call in file.content.service_locator_calls),
        ]

    @cached_property
    def antipatterns(self) -> dict[str, int]:
        totals = dict.fromkeys(("magicKeys", "deepArrays", "serviceLocators"), 0)
        for score in self.antipattern_scores:
            totals[score.pattern] += score.score
        return totals

    # =============================================================================
    # HOTSPOTS
    # =============================================================================

    @cached_property
    def function_hotspots(self) -> list[dict]:
        """The HOTSPOT_COUNT functions hardest to read, by cognitive complexity; ties in file and
        declaration order."""
        ranked = sorted(self.production_functions,
                        key=lambda function: (-function.declaration.cognitive, function.file.path, function.position))
        return [hotspot(function.name, [function]) for function in ranked[:HOTSPOT_COUNT]]

    @cached_property
    def class_hotspots(self) -> list[dict]:
        """The HOTSPOT_COUNT classes hardest to read, by the cognitive complexity of their methods
        together; ties in file and declaration order. A class is its declaration, so two classes
        sharing a name are two entries."""
        classes = collections.defaultdict(list)
        for function in self.production_functions:
            if function.declaration.kind == "method":
                classes[function.declaration.parent].append(function)
        ranked = sorted(classes.items(), key=lambda item: (
            -sum(method.declaration.cognitive for method in item[1]), item[1][0].file.path,
            min(method.position for method in item[1])))
        return [hotspot(declaration.name or "anonymous", methods) for declaration, methods in ranked[:HOTSPOT_COUNT]]

    # =============================================================================
    # TYPE COVERAGE
    # =============================================================================

    @cached_property
    def api_methods(self) -> list[Declaration]:
        """The API a developer reads from signatures: public methods, interface signatures included, leaving
        out hook implementations,
        which the hook system calls and which arrived fully typed in Drupal 11."""
        methods = []
        for file in self.production_php:
            implementations = hook_implementations(file.content)
            methods += [declaration for declaration in file.content.declarations
                        if declaration.kind == "method" and declaration.visibility == "public"
                        and declaration not in implementations]
        return methods

    @cached_property
    def type_coverage(self) -> dict[str, int]:
        """Type coverage: how many parameters and return values of the API declare a type, and how many a
        precise one. A type is imprecise when, leaving out null, it is a single array, mixed, iterable,
        object or callable. Constructors and destructors cannot declare a return type, so they have no
        return value here."""
        def precise(types: tuple[str, ...]) -> bool:
            named = [name for name in types if name != "null"]
            return not (len(named) == 1 and named[0] in {"array", "mixed", "iterable", "object", "callable"})
        parameters = [types for method in self.api_methods for types in method.parameter_types]
        returns = [method.return_type for method in self.api_methods
                   if method.name.lower() not in {"__construct", "__destruct"}]
        coverage = {}
        for prefix, declared in (("parameter", parameters), ("return", returns)):
            coverage[f"{prefix}Total"] = len(declared)
            coverage[f"{prefix}Typed"] = sum(types is not None for types in declared)
            coverage[f"{prefix}Precise"] = sum(types is not None and precise(types) for types in declared)
        return coverage

    # =============================================================================
    # DEPRECATIONS
    # =============================================================================

    @cached_property
    def deprecations(self) -> dict[str, int]:
        """Deprecated API awaiting removal: declarations with an @deprecated annotation line in their
        docblock or PHP's #[\\Deprecated] attribute, and services and asset libraries marked deprecated:
        in YAML."""
        categories = {"method": "methods", "function": "functions", "property": "properties",
                      "class_constant": "constants", "constant": "constants"}
        counts = dict.fromkeys(("classes", "methods", "functions", "properties", "constants", "services", "libraries"), 0)
        for _, declaration in self.production_declarations:
            if (re.search(r"^[ \t*/]*@deprecated\b", declaration.doc or "", re.MULTILINE | re.ASCII)
                    or any(attribute.name == "Deprecated" for attribute in declaration.attributes)):
                counts[categories.get(declaration.kind, "classes")] += 1
        for file in self.own_files:
            if file.path.endswith((".services.yml", ".libraries.yml")) and not is_test_code(file.path):
                category = "services" if file.path.endswith(".services.yml") else "libraries"
                counts[category] += file.content.deprecated_key_count
        return counts

    # =============================================================================
    # SURFACE AREA
    # =============================================================================

    @cached_property
    def plugin_types(self) -> list[str]:
        """Plugin types: classes extending Drupal's DefaultPluginManager."""
        return sorted({declaration.name or "anonymous" for _, declaration in self.production_declarations
                       if "Drupal\\Core\\Plugin\\DefaultPluginManager" in declaration.extends})

    @cached_property
    def documented_hooks(self) -> list[str]:
        """Hooks: the ones Core documents, every function hook_NAME() in an .api.php file, placeholders
        included (hook_ENTITY_TYPE_insert). Core began documenting hooks in its own repository in the
        Drupal 7 cycle, so earlier snapshots have none. Read from the text rather than the syntax tree:
        help.api.php, the only file documenting hook_help in January 2015, had lost its opening <?php
        tag, and documentation need not be valid PHP to document."""
        return sorted({name for file in self.own_files
                       if file.path.endswith(".api.php") and not is_test_code(file.path)
                       for name in file.content.text_functions if name.startswith("hook_")})

    @cached_property
    def magic_key_vocabulary(self) -> list[str]:
        """The magic-key vocabulary: distinct magic keys set in array literals, leaving out the common
        element properties every form uses."""
        return sorted({use.name for _, use in self.magic_key_uses
                       if use.syntax == "literal"
                       and use.name not in {"#type", "#markup", "#title", "#weight", "#prefix", "#suffix", "#attributes",
                                            "#default_value", "#description", "#required", "#options", "#rows", "#cols",
                                            "#size", "#maxlength", "#placeholder", "#cache", "#attached", "#value", "#name",
                                            "#id", "#disabled", "#min", "#max", "#step", "#multiple", "#empty_option",
                                            "#empty_value"}})

    @cached_property
    def event_subscribers(self) -> set[Declaration]:
        """The classes that subscribe to events: they implement EventSubscriberInterface, or extend a
        class that does. Reading each class on its own missed the twelve that name the interface
        nowhere, eleven of them children of RouteSubscriberBase."""
        by_name = {declaration.resolved_name: declaration
                   for file in self.php_sources for declaration in file.content.declarations
                   if declaration.kind in CLASS_LIKE_KINDS and declaration.resolved_name is not None}
        subscribers = {declaration for declaration in by_name.values()
                       if EVENT_SUBSCRIBER_INTERFACE in declaration.implements}
        while True:
            inheriting = {declaration for declaration in by_name.values() if declaration not in subscribers
                          and any(by_name.get(parent) in subscribers for parent in declaration.extends)}
            if not inheriting:
                return subscribers
            subscribers |= inheriting

    @cached_property
    def subscribed_events(self) -> list[str]:
        """Events: the keys an event subscriber's getSubscribedEvents() method subscribes to, as written."""
        return sorted({event.name for file in self.production_php for event in file.content.subscribed_event_keys
                       if event.function.parent in self.event_subscribers})

    @cached_property
    def service_types(self) -> list[str]:
        """Service types: the prefix of each service a services file defines (entity_type.manager is
        entity_type). A service is a lowercase id whose definition follows on the lines below it; an
        alias written on its own line and a service named by its class are not counted."""
        return sorted({service.name.partition(".")[0] for file in self.own_files
                       if file.path.endswith(".services.yml") and not is_test_code(file.path)
                       for service in file.content.service_keys
                       if re.fullmatch(r"[a-z][a-z0-9_.]+", service.name, re.ASCII) and service.value is None})

    @cached_property
    def interface_methods(self) -> list[str]:
        """Interface methods: every method of an interface, as Interface::method."""
        return sorted({f"{declaration.parent.name}::{declaration.name}" for _, declaration in self.production_declarations
                       if declaration.kind == "method" and declaration.parent.kind == "interface"})

    @cached_property
    def global_functions(self) -> list[str]:
        """Global functions: the procedural functions a developer calls. Left out are the ones Drupal
        calls by name: implementations, which say so in their docblock ("Implements hook_help().",
        "Implementation of hook_help()." in Drupal 6, a hook's parentheses sometimes left off); install
        and update functions, the whole of .install and .post_update.php files; and
        template_preprocess_HOOK and template_process_HOOK, the conventions theme.api.php documents.
        Functions starting with _ are internal. Recognizing implementations by name instead turned API
        functions such as contact_load() into hooks."""
        return sorted({declaration.name for file, declaration in self.production_declarations
                       if declaration.kind == "function"
                       and not file.path.endswith((".install", ".post_update.php"))
                       and not declaration.name.startswith("_")
                       and not re.search(r"\bImplement(?:s|ation)?(?: of)?\s+(?:hook_\w+|\w+\(\))", declaration.doc or "", re.ASCII)
                       and not re.match(r"template_(pre)?process(_|$)", declaration.name, re.ASCII)})

    # =============================================================================
    # YAML FORMATS
    # =============================================================================

    @cached_property
    def extension_yaml(self) -> list[tuple[str, str]]:
        """YAML files inside an extension, as (extension, path), paired with the nearest one above them.
        An extension is a directory holding <name>.info.yml, or <name>.info until Drupal 8 moved extension
        info to YAML in 2013; reading only .info.yml left January 2013 with no formats at all."""
        extensions = {directory_name(file.path) for file in self.own_files
                      if base_name(file.path) in {base_name(directory_name(file.path)) + suffix
                                                  for suffix in (".info.yml", ".info")}}
        pairs = []
        for file in self.own_files:
            if isinstance(file.content, YamlContent) and not is_test_code(file.path):
                directory = directory_name(file.path)
                while directory not in extensions and directory != ".":
                    directory = directory_name(directory)
                if directory in extensions:
                    pairs.append((directory, file.path))
        return pairs

    @cached_property
    def yaml_formats(self) -> list[str]:
        """YAML formats: the kinds of YAML file extensions ship, read from the files (yaml_format).
        Detecting formats from discovery class names lost four when Core renamed a class and never found
        components."""
        return sorted({format for extension, path in self.extension_yaml
                       if (format := yaml_format(extension, path)) is not None})

    # =============================================================================
    # DATA.JSON
    # =============================================================================

    def fields(self) -> dict:
        """The snapshot's codebase fields in data.json."""
        return {
            "production": {
                "lines": self.production_lines,
                "objectOrientedLines": self.object_oriented_lines,
                "cognitive": self.cognitive_complexity,
                "lcom4": self.class_cohesion,
                "antipatterns": self.antipatterns,
                "typeCoverage": self.type_coverage,
            },
            "test": {"lines": self.test_lines},
            "js": {"lines": self.javascript_lines},
            "dependencies": self.dependencies,
            "surfaceArea": {
                "pluginTypes": self.plugin_types,
                "hooks": self.documented_hooks,
                "magicKeys": self.magic_key_vocabulary,
                "events": self.subscribed_events,
                "services": self.service_types,
                "yamlFormats": self.yaml_formats,
                "interfaceMethods": self.interface_methods,
                "globalFunctions": self.global_functions,
            },
            "deprecations": self.deprecations,
            "hotspots": {"functions": self.function_hotspots, "classes": self.class_hotspots},
        }

    def production_code_lines(self) -> dict[str, list[int]]:
        """The line numbers counted as production PHP in each file, by path from the repository root:
        what source code age dates with git blame."""
        return {file.prefix + file.path: [line for first, last in file.content.code_line_runs
                                          for line in range(first, last + 1)]
                for file in self.production_php}


def hotspot(name: str, functions: list[Function]) -> dict:
    return {"name": name, "file": functions[0].file.path,
            "cognitive": sum(function.declaration.cognitive for function in functions),
            "cyclomatic": sum(function.declaration.cyclomatic for function in functions),
            "antipatterns": sum(function.antipatterns for function in functions)}
